message = {
    'content_type': 'text',
    'id': 59, 'message_id': 59,
    'from_user': {
        'id': 1652127583,
        'is_bot': False,
        'first_name': 'Artem',
        'username': 'cha_artem',
        'last_name': 'CHA',
        'language_code': 'en',
        'can_join_groups': None,
        'can_read_all_group_messages': None,
        'supports_inline_queries': None
    },
    'date': 1629302662,
    'chat': {
        'id': 1652127583,
        'type': 'private',
        'title': None,
        'username': 'cha_artem',
        'first_name': 'Artem',
        'last_name': 'CHA',
        'photo': None,
        'bio': None,
        'description': None,
        'invite_link': None,
        'pinned_message': None,
        'permissions': None,
        'slow_mode_delay': None,
        'message_auto_delete_time': None,
        'sticker_set_name': None,
        'can_set_sticker_set': None,
        'linked_chat_id': None,
        'location': None
    },
    'forward_from': None,
    'forward_from_chat': None,
    'forward_from_message_id': None,
    'forward_signature': None,
    'forward_sender_name': None,
    'forward_date': None,
    'reply_to_message': None,
    'via_bot': None,
    'edit_date': None,
    'media_group_id': None,
    'author_signature': None,
    'text': '/start',
    # 'entities': [<telebot.types.MessageEntity object at 0x7fe382cd5df0>],
    'caption_entities': None,
    'audio': None,
    'document': None,
    'photo': None,
    'sticker': None,
    'video': None,
    'video_note': None,
    'voice': None,
    'caption': None,
    'contact': None,
    'location': None,
    'venue': None,
    'animation': None,
    'dice': None,
    'new_chat_member': None,
    'new_chat_members': None,
    'left_chat_member': None,
    'new_chat_title': None,
    'new_chat_photo': None,
    'delete_chat_photo': None,
    'group_chat_created': None,
    'supergroup_chat_created': None,
    'channel_chat_created': None,
    'migrate_to_chat_id': None,
    'migrate_from_chat_id': None,
    'pinned_message': None,
    'invoice': None,
    'successful_payment': None,
    'connected_website': None,
    'reply_markup': None,
    'json': {
        'message_id': 59,
        'from': {
            'id': 1652127583,
            'is_bot': False,
            'first_name': 'Artem',
            'last_name': 'CHA',
            'username': 'cha_artem',
            'language_code': 'en'
        },
        'chat': {
            'id': 1652127583,
            'first_name': 'Artem',
            'last_name': 'CHA',
            'username': 'cha_artem',
            'type': 'private'
        },
        'date': 1629302662,
        'text': '/start',
        'entities': [{'offset': 0, 'length': 6, 'type': 'bot_command'}]
    }
}
